/**
 * SLPP New England Chapter — Ticket Voucher Backend
 * ------------------------------------------------
 * Three user groups, three sheets that reflect them:
 *
 *   ADMIN        generates vouchers and hands them to a DISTRIBUTOR.
 *                Even a single ticket is a "batch of 1" — there is no
 *                separate "solo invite" concept anymore. One admin action,
 *                one distributor link, any size from 1 to 10.
 *
 *   DISTRIBUTOR  opens that one link, sees every voucher in the batch,
 *                and either shares each one to a different CLAIMANT via
 *                Text/WhatsApp, or claims one for themselves directly.
 *                Once a voucher is sent OR claimed, it's done — no
 *                re-sending, no double use.
 *
 *   CLAIMANT     opens their individual voucher link (or the open public
 *                form) and fills in their own details to receive a ticket.
 *
 * On event day, a separate concern — CHECK-IN — happens at the door:
 *   - A guest who already has a ticket presents their serial number.
 *   - A walk-in guest with no prior ticket buys one on the spot.
 * Both end up in the CheckIns sheet with Name/Chapter/Tier/Phone/Payment
 * Status, which is deliberately separate from Claims — Claims tracks who
 * holds a valid ticket number, CheckIns tracks who is actually AT the
 * event and whether they've paid. A walk-in gets both: a real Claims
 * entry (so ticket counts stay accurate) and a CheckIns entry.
 *
 * FOUR SHEETS:
 *   Claims    — every ticket ever issued (any source)
 *   Counter   — single cell, the next ticket number to hand out
 *   Vouchers  — every voucher ever generated by an admin, batched
 *   CheckIns  — every person confirmed physically present at the door
 *
 * SETUP:
 * 1. Create a new Google Sheet.
 * 2. Extensions → Apps Script. Delete any starter code, paste this file in.
 * 3. Run `setupSheets()` once (creates all four sheets + two dashboards).
 * 4. Deploy → New deployment → Web app → Execute as Me → Access: Anyone.
 * 5. Copy the Web App URL into claim.html's CONFIG.ENDPOINT.
 * 6. Set BASE_CLAIM_URL below to your real GitHub Pages claim.html URL.
 */

const CLAIMS_SHEET_NAME = 'Claims';
const COUNTER_SHEET_NAME = 'Counter';
const VOUCHERS_SHEET_NAME = 'Vouchers';
const CHECKINS_SHEET_NAME = 'CheckIns';
const SETTINGS_SHEET_NAME = 'Settings';
const EVENTCONFIG_SHEET_NAME = 'EventConfig';

// TODO: set this to your real GitHub Pages URL once claim.html is live.
const BASE_CLAIM_URL = 'https://greenprofessionals.github.io/slpp-ne-tickets/claim.html';
// The lean, admin-free, no-preview-image page used for every voucher/batch
// link actually sent to a distributor or claimant. Keeps admin tools and
// rich link previews off anything that leaves your hands.
const BASE_VOUCHER_URL = 'https://greenprofessionals.github.io/slpp-ne-tickets/v.html';

/**
 * Admin passcodes — backend-only, never appears on the public claim.html
 * page. Used to identify who performed an action (for logging) and to
 * gate every admin/distributor/gate action reachable from the web panel.
 */
const ADMIN_DIRECTORY = {
  'kulane2026': 'Kula Sillah — New England Chapter (NEC)',
  'fombany2026': 'Test Admin (testing number)'
};

/** Live tier keys, read from Settings each time — not a fixed array. Any number of tiers works. */
function validTierKeys() {
  return Object.keys(getTierConfig());
}

function digitsOnly(str) {
  return (str || '').toString().replace(/\D/g, '');
}

/**
 * Reads current tier labels/prices from the Settings sheet. This is the
 * single source of truth — nothing else in this file hardcodes a price.
 * If Settings is missing or malformed, falls back to sane defaults so a
 * fresh/broken sheet never crashes the whole system.
 */
function getTierConfig() {
  const fallback = {
    single: { label: 'Single', price: 100 },
    patron: { label: 'Single Patron', price: 150 },
    double: { label: 'Double Patron', price: 250 }
  };
  try {
    const formResponse = getLatestFormResponse();
    if (formResponse) {
      const config = {};
      for (let i = 1; i <= 5; i++) {
        const name = (formResponse[`Tier${i}Name`] || '').toString().trim();
        if (!name) continue;
        const price = Number(formResponse[`Tier${i}Price`]) || 0;
        const key = name.toLowerCase().replace(/[^a-z0-9]+/g, '') || `tier${i}`;
        config[key] = { label: name, price: price };
      }
      if (Object.keys(config).length) return config;
    }

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(SETTINGS_SHEET_NAME);
    if (!sheet) return applyUploadedBrandAssets_(fallback);
    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return applyUploadedBrandAssets_(fallback);
    const config = {};
    sheet.getRange(2, 1, lastRow - 1, 3).getValues().forEach(row => {
      const key = (row[0] || '').toString().trim().toLowerCase();
      if (!key) return;
      config[key] = { label: (row[1] || key).toString().trim(), price: Number(row[2]) || 0 };
    });
    return Object.keys(config).length ? config : fallback;
  } catch (e) {
    return fallback;
  }
}

/**
 * Reads event/chapter branding from the EventConfig sheet (key-value pairs).
 * This is what makes the whole system reusable by any chapter — swap these
 * values and the page header + generated ticket both rebrand automatically,
 * no code or artwork changes needed.
 */
function getEventConfig() {
  const fallback = {
    OrgName: 'SLPP North America',
    ChapterName: 'New England Chapter',
    EventTitle: 'Executive Inauguration Celebration',
    Tagline: 'Celebrating the Inauguration of the Executive of the New England Chapter',
    EventDate: 'Saturday, August 22, 2026',
    EventTime: '6:00 PM',
    VenueName: 'Prince Hall Grand Lodge',
    VenueAddress: '24 Washington St, Dorchester, MA, 02121',
    ContactPhone: '(678) 301-8876',
    WebsiteURL: 'https://greenprofessionals.github.io/slpp_new_england_chapter.html',
    DressCode: 'Formal / Traditional',
    PrimaryColor: '#0b3d24',
    GoldColor: '#c9a24b',
    LogoURL: '',
    BackgroundURL: '',
    GroupLabel: 'Chapter',
    UseGroups: 'true',
    SerialPrefix: 'MA-',
    CurrencySymbol: '$',
    FooterLegalText: 'Ticket must be presented for admission · No refunds or replacements',
    MaxBatchSize: '10'
  };
  try {
    // The config Form, if it's been submitted at least once, wins over the
    // manually-edited EventConfig sheet — this is the intended "configure
    // via Form, not by touching the Sheet" path.
    const formResponse = getLatestFormResponse();
    if (formResponse) {
      const cfg = Object.assign({}, fallback);
      Object.keys(fallback).forEach(key => {
        const v = formResponse[key];
        if (v !== undefined && v !== null && v.toString().trim() !== '') {
          cfg[key] = normalizeConfigValue(key, v);
        }
      });
      if (formResponse['LogoImage']) {
        const embedded = driveUploadToDataUrl(formResponse['LogoImage']);
        if (embedded) cfg.LogoURL = embedded;
      }
      if (formResponse['BackgroundImage']) {
        const embedded = driveUploadToDataUrl(formResponse['BackgroundImage']);
        if (embedded) cfg.BackgroundURL = embedded;
      }
      return applyUploadedBrandAssets_(cfg);
    }

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(EVENTCONFIG_SHEET_NAME);
    if (!sheet) return fallback;
    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return fallback;
    const config = Object.assign({}, fallback);
    sheet.getRange(2, 1, lastRow - 1, 2).getValues().forEach(row => {
      const key = (row[0] || '').toString().trim();
      if (!key) return;
      const value = (row[1] || '').toString().trim();
      if (value) config[key] = value;
    });
    return applyUploadedBrandAssets_(config);
  } catch (e) {
    return applyUploadedBrandAssets_(fallback);
  }
}

const GROUPS_SHEET_NAME = 'Groups';
const CONFIG_FORM_RESPONSES_SHEET = 'ConfigFormResponses';

/**
 * Reads the MOST RECENT submission of the configuration Google Form (see
 * createConfigForm()) as a plain { headerText: value } object. Returns
 * null if the form hasn't been created/submitted yet — every config
 * getter below treats that as "fall back to the old sheet-based config,"
 * so nothing breaks for a deployment that hasn't switched to the form.
 */
function getLatestFormResponse() {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CONFIG_FORM_RESPONSES_SHEET);
    if (!sheet) return null;
    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return null;
    const lastCol = sheet.getLastColumn();
    const headers = sheet.getRange(1, 1, 1, lastCol).getValues()[0];
    const values = sheet.getRange(lastRow, 1, 1, lastCol).getValues()[0];
    const result = {};
    headers.forEach((h, i) => { result[h] = values[i]; });
    return result;
  } catch (e) {
    return null;
  }
}

/** Normalize Google Forms/Sheets date and time values for display. */
function normalizeConfigValue(key, value) {
  if (value === null || value === undefined) return '';
  if (Object.prototype.toString.call(value) === '[object Date]' && !isNaN(value.getTime())) {
    const tz = Session.getScriptTimeZone() || 'America/New_York';
    if (key === 'EventDate') return Utilities.formatDate(value, tz, 'EEEE, MMMM d, yyyy');
    if (key === 'EventTime') return Utilities.formatDate(value, tz, 'h:mm a');
  }
  const raw = String(value).trim();
  if (key === 'EventTime') {
    const m = raw.match(/\b(\d{1,2}):(\d{2})(?::\d{2})?\b/);
    if (m && /1899|GMT|Standard Time|Daylight Time/i.test(raw)) {
      let h = Number(m[1]);
      const min = m[2];
      const suffix = h >= 12 ? 'PM' : 'AM';
      h = h % 12 || 12;
      return `${h}:${min} ${suffix}`;
    }
  }
  if (key === 'EventDate') {
    const d = new Date(raw);
    if (!isNaN(d.getTime())) {
      const tz = Session.getScriptTimeZone() || 'America/New_York';
      return Utilities.formatDate(d, tz, 'EEEE, MMMM d, yyyy');
    }
  }
  return raw;
}

/** Convert a Google Forms file-upload answer to an embeddable data URL. */
function driveUploadToDataUrl(url) {
  if (!url) return '';
  const match = url.toString().match(/[-\w]{25,}/);
  if (!match) return '';
  try {
    const blob = DriveApp.getFileById(match[0]).getBlob();
    const mime = blob.getContentType() || 'image/png';
    return `data:${mime};base64,${Utilities.base64Encode(blob.getBytes())}`;
  } catch (e) {
    return '';
  }
}


/** Read an uploaded branding asset stored by this web app and return a data URL. */
function uploadedAssetDataUrl_(propertyKey) {
  try {
    const fileId = PropertiesService.getScriptProperties().getProperty(propertyKey);
    if (!fileId) return '';
    const blob = DriveApp.getFileById(fileId).getBlob();
    const mime = blob.getContentType() || 'image/png';
    return `data:${mime};base64,${Utilities.base64Encode(blob.getBytes())}`;
  } catch (e) {
    return '';
  }
}

/** Uploaded assets from config.html take priority over URL/form fallbacks. */
function applyUploadedBrandAssets_(cfg) {
  const logo = uploadedAssetDataUrl_('TICKET_LOGO_FILE_ID');
  if (logo) cfg.LogoURL = logo;
  return cfg;
}

/** Save a logo uploaded from config.html. */
function uploadLogoWeb(body) {
  const issuedBy = requireAdmin(body.adminPasscode);
  if (!issuedBy) return { ok: false, error: 'Incorrect admin passcode.' };

  const dataUrl = (body.dataUrl || '').toString();
  const fileName = (body.fileName || 'ticket-logo.png').toString().replace(/[^a-zA-Z0-9._-]/g, '_');
  const match = dataUrl.match(/^data:(image\/(?:png|jpeg|jpg|webp));base64,([A-Za-z0-9+/=]+)$/i);
  if (!match) return { ok: false, error: 'Choose a PNG, JPG, JPEG, or WebP logo image.' };

  const bytes = Utilities.base64Decode(match[2]);
  const maxBytes = 2 * 1024 * 1024;
  if (bytes.length > maxBytes) return { ok: false, error: 'Logo is too large. Please use an image smaller than 2 MB.' };

  const mime = match[1].toLowerCase() === 'image/jpg' ? 'image/jpeg' : match[1].toLowerCase();
  const blob = Utilities.newBlob(bytes, mime, fileName);

  let folder;
  const folders = DriveApp.getFoldersByName('Ticket System Assets');
  folder = folders.hasNext() ? folders.next() : DriveApp.createFolder('Ticket System Assets');
  const file = folder.createFile(blob);

  const props = PropertiesService.getScriptProperties();
  const oldId = props.getProperty('TICKET_LOGO_FILE_ID');
  props.setProperty('TICKET_LOGO_FILE_ID', file.getId());
  if (oldId && oldId !== file.getId()) {
    try { DriveApp.getFileById(oldId).setTrashed(true); } catch (e) { /* keep going */ }
  }

  return { ok: true, fileName: file.getName(), uploadedBy: issuedBy };
}

/** Converts a Google Forms file-upload response (a Drive file URL) into a directly-embeddable image URL, and makes the file viewable so a browser can actually load it. */
function driveUrlToDirectImage(url) {
  if (!url) return '';
  const match = url.toString().match(/[-\w]{25,}/);
  if (!match) return '';
  const fileId = match[0];
  try {
    DriveApp.getFileById(fileId).setSharing(DriveApp.Access.ANYONE_WITH_LINK, DriveApp.Permission.VIEW);
  } catch (e) { /* best-effort — if this fails the image just won't load, non-fatal */ }
  return `https://drive.google.com/uc?export=view&id=${fileId}`;
}



/**
 * Reads the list of group/chapter options from the Groups sheet — one
 * name per row. This is what lets the dropdown be arbitrary categories
 * for ANY event (teams, tables, regions), not a fixed SLPP chapter list.
 * Falls back to the current SLPP chapter list only if the sheet is
 * missing entirely, so the existing New England deployment never breaks.
 */
function getGroups() {
  const fallback = [
    'No Chapter', 'Arizona Chapter (AZC)', 'Atlanta GA Chapter (GAC)', 'Chicago Chapter (ILC)',
    'Dallas Chapter (TXDC)', 'Delaware Valley Chapter (DVC)', 'DRC Chapter (DRC)', 'Florida Chapter (FLC)',
    'Houston Chapter (TXHC)', 'Iowa Chapter (IAC)', 'Minnesota Chapter (MNC)', 'New England Chapter (NEC)',
    'New Jersey Chapter (NJC)', 'New York Chapter (NYC)', 'North Dakota Chapter (NDC)',
    'Northern California Chapter (CANC)', 'Ohio Chapter (OHC)', 'Seattle Washington Chapter (SWC)',
    'Southern California Chapter (CASC)', 'Virginia Chapter (VAC)', 'Washington DC Chapter (WDC)'
  ];
  try {
    const formResponse = getLatestFormResponse();
    if (formResponse && formResponse['GroupsList']) {
      const names = formResponse['GroupsList'].toString().split('\n').map(s => s.trim()).filter(Boolean);
      if (names.length) return names;
    }

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(GROUPS_SHEET_NAME);
    if (!sheet) return fallback;
    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return fallback;
    const names = sheet.getRange(2, 1, lastRow - 1, 1).getValues()
      .map(r => (r[0] || '').toString().trim())
      .filter(Boolean);
    return names.length ? names : fallback;
  } catch (e) {
    return fallback;
  }
}

/** Looks up a passcode, never blocks — used only for Sheet-menu tools where Editor access already implies trust. */
function identifyAdmin(passcode) {
  const key = (passcode || '').toString().trim().toLowerCase();
  return ADMIN_DIRECTORY[key] || (passcode ? 'Unrecognized admin (invalid passcode)' : 'Unknown admin');
}

/** Returns the directory name if valid, or null — used by every public web endpoint, and DOES block on a miss. */
function requireAdmin(passcode) {
  const key = (passcode || '').toString().trim().toLowerCase();
  return ADMIN_DIRECTORY[key] || null;
}

function onOpen() {
  SpreadsheetApp.getUi()
    .createMenu('SLPP Tickets')
    .addItem('Generate Vouchers (for a distributor)', 'menuGenerateVouchers')
    .addSeparator()
    .addItem('Check In: Guest With Ticket', 'menuCheckInWithTicket')
    .addItem('Check In: Walk-In (sell + check in)', 'menuCheckInWalkIn')
    .addItem('View Check-In Summary', 'menuViewCheckInSummary')
    .addSeparator()
    .addItem('Show next ticket number', 'adminShowNextNumber')
    .addItem('Refresh Dashboard Charts', 'refreshDashboards')
    .addSeparator()
    .addItem('Create Configuration Form (one-time)', 'createConfigForm')
    .addToUi();
}

/** One-time setup: creates all four sheets with headers, plus both dashboards. */
function setupSheets() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();

  let claims = ss.getSheetByName(CLAIMS_SHEET_NAME);
  if (!claims) claims = ss.insertSheet(CLAIMS_SHEET_NAME);
  claims.clear();
  claims.getRange(1, 1, 1, 11).setValues([[
    'Timestamp', 'Ticket Number', 'Serial', 'Tier', 'Full Name', 'Email', 'Phone', 'Chapter', 'Source', 'Issued By', 'Check-In Token'
  ]]);
  claims.setFrozenRows(1);

  let counter = ss.getSheetByName(COUNTER_SHEET_NAME);
  if (!counter) counter = ss.insertSheet(COUNTER_SHEET_NAME);
  counter.clear();
  counter.getRange('A1').setValue(0);

  let vouchers = ss.getSheetByName(VOUCHERS_SHEET_NAME);
  if (!vouchers) vouchers = ss.insertSheet(VOUCHERS_SHEET_NAME);
  vouchers.clear();
  vouchers.getRange(1, 1, 1, 16).setValues([[
    'Token', 'Batch ID', 'Tier (blank = claimant chooses)', 'Chapter (blank = claimant chooses)',
    'Name (hint, single-voucher batches only)', 'Phone (hint, single-voucher batches only)',
    'Created At', 'Issued By', 'Dispatched', 'Dispatched At', 'Claimed', 'Claimed At',
    'Resulting Serial', 'Resulting Tier', 'Sent To Email', 'Sent To Phone'
  ]]);
  vouchers.setFrozenRows(1);

  let checkins = ss.getSheetByName(CHECKINS_SHEET_NAME);
  if (!checkins) checkins = ss.insertSheet(CHECKINS_SHEET_NAME);
  checkins.clear();
  checkins.getRange(1, 1, 1, 8).setValues([[
    'Timestamp', 'Name', 'Chapter', 'Tier', 'Phone', 'Payment Status', 'Linked Serial', 'Checked In By'
  ]]);
  checkins.setFrozenRows(1);

  // Settings is deliberately NOT cleared if it already exists — re-running
  // setupSheets() should never wipe out a price you've already edited here.
  let settings = ss.getSheetByName(SETTINGS_SHEET_NAME);
  if (!settings) {
    settings = ss.insertSheet(SETTINGS_SHEET_NAME);
    settings.getRange(1, 1, 1, 3).setValues([['Tier Key', 'Label', 'Price ($)']]);
    settings.getRange(2, 1, 3, 3).setValues([
      ['single', 'Single', 100],
      ['patron', 'Single Patron', 150],
      ['double', 'Double Patron', 250]
    ]);
    settings.setFrozenRows(1);
  }

  // Same non-destructive treatment — this is chapter/event branding, edited
  // by hand once per event, never something a setup re-run should reset.
  let eventConfig = ss.getSheetByName(EVENTCONFIG_SHEET_NAME);
  if (!eventConfig) {
    eventConfig = ss.insertSheet(EVENTCONFIG_SHEET_NAME);
    const defaults = getEventConfig();
    eventConfig.getRange(1, 1, 1, 2).setValues([['Key', 'Value']]);
    const rows = Object.keys(defaults).map(k => [k, defaults[k]]);
    eventConfig.getRange(2, 1, rows.length, 2).setValues(rows);
    eventConfig.setFrozenRows(1);
    eventConfig.setColumnWidth(2, 400);
  }

  // Also non-destructive — seeded with the current SLPP chapter list so
  // the live deployment keeps working unchanged; edit or replace freely
  // for a different event's own categories.
  let groups = ss.getSheetByName(GROUPS_SHEET_NAME);
  if (!groups) {
    groups = ss.insertSheet(GROUPS_SHEET_NAME);
    groups.getRange(1, 1, 1, 1).setValues([['Group Name']]);
    const names = getGroups();
    groups.getRange(2, 1, names.length, 1).setValues(names.map(n => [n]));
    groups.setFrozenRows(1);
  }

  buildClaimsVsVouchersChart();
  buildClaimsByChapterChart();
  buildVouchersByStatusChart();
  buildTicketsByTierChart();
  buildRevenueByChapterChart();
}

// ============================================================
// TICKET ISSUANCE — the one function that actually hands out a
// number. Every path (public form, voucher claim, walk-in sale)
// goes through here, so numbers can never collide or repeat.
// ============================================================

function issueTicket(fullName, email, phone, chapter, tier, source, voucherToken, issuedBy, confirmDuplicate) {
  const lock = LockService.getScriptLock();
  lock.waitLock(30000);

  try {
    fullName = (fullName || '').toString().trim();
    email = (email || '').toString().trim();
    phone = (phone || '').toString().trim();
    chapter = (chapter || 'No Chapter').toString().trim();
    tier = (tier || '').toString().trim().toLowerCase();

    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const claimsSheet = ss.getSheetByName(CLAIMS_SHEET_NAME);
    const counterSheet = ss.getSheetByName(COUNTER_SHEET_NAME);

    // Only TIER is ever enforced from a voucher. Name/phone/chapter are
    // prefill-only conveniences — whatever the claimant actually submits
    // for those is what's saved, since none of them show as locked.
    let voucherRowIndex = -1;
    let vouchersSheet = null;
    if (voucherToken) {
      vouchersSheet = ss.getSheetByName(VOUCHERS_SHEET_NAME);
      const data = vouchersSheet.getDataRange().getValues();
      let voucher = null;
      for (let i = 1; i < data.length; i++) {
        if (data[i][0] === voucherToken) { voucherRowIndex = i; voucher = data[i]; break; }
      }
      if (!voucher) return { ok: false, error: 'This voucher link is not valid.' };

      const voucherTier = voucher[2];
      const claimed = voucher[10];
      if (claimed === true || claimed === 'TRUE') {
        const resultSerial = voucher[12] || null;
        return {
          ok: false,
          alreadyClaimed: true,
          error: 'This voucher has already been claimed.',
          serial: resultSerial,
          tier: voucher[13] || null,
          checkInToken: resultSerial ? getCheckInTokenForSerial(resultSerial) : null
        };
      }
      if (voucherTier) tier = voucherTier.toString().toLowerCase();
    }

    if (!tier) tier = 'single';
    if (!validTierKeys().includes(tier)) return { ok: false, error: 'Invalid ticket type.' };
    if (!fullName) return { ok: false, error: 'Full name is required.' };

    // Soft duplicate check: only the open public form, only with contact info given.
    if (!voucherToken && source === 'form' && !confirmDuplicate && (email || phone)) {
      const existingRows = claimsSheet.getLastRow() > 1
        ? claimsSheet.getRange(2, 6, claimsSheet.getLastRow() - 1, 2).getValues()
        : [];
      const emailNorm = email.toLowerCase();
      const phoneNorm = digitsOnly(phone);
      const isDuplicate = existingRows.some(row => {
        const rowEmail = (row[0] || '').toString().toLowerCase();
        const rowPhone = digitsOnly(row[1]);
        return (emailNorm && rowEmail === emailNorm) || (phoneNorm && rowPhone === phoneNorm);
      });
      if (isDuplicate) {
        return { ok: false, duplicateWarning: true, error: 'This phone number or email has already claimed a ticket.' };
      }
    }

    const current = Number(counterSheet.getRange('A1').getValue()) || 0;
    const nextNumber = current + 1;
    counterSheet.getRange('A1').setValue(nextNumber);
    const prefix = getEventConfig().SerialPrefix || 'MA-';
    const serial = prefix + String(nextNumber).padStart(3, '0');
    // A long random secret, NOT the sequential serial, is what actually goes
    // in the QR code — the serial space is tiny (3 digits) and trivially
    // guessable; a UUID gives 2^128 possibilities, effectively unguessable.
    const checkInToken = Utilities.getUuid().replace(/-/g, '');

    claimsSheet.appendRow([new Date(), nextNumber, serial, tier, fullName, email, phone, chapter, source || 'form', issuedBy || '', checkInToken]);

    if (voucherToken && vouchersSheet && voucherRowIndex > -1) {
      vouchersSheet.getRange(voucherRowIndex + 1, 11).setValue(true);       // Claimed
      vouchersSheet.getRange(voucherRowIndex + 1, 12).setValue(new Date()); // Claimed At
      vouchersSheet.getRange(voucherRowIndex + 1, 13).setValue(serial);     // Resulting Serial
      vouchersSheet.getRange(voucherRowIndex + 1, 14).setValue(tier);       // Resulting Tier
    }

    // Email backup: if the claimant gave an email, send a copy of the key
    // details + (for voucher claims) a link that reopens their ticket any
    // time. This is the safety net for "I claimed it but never saved it."
    if (email) {
      try {
        const cfg = getEventConfig();
        const reopenLine = voucherToken
          ? `<p>You can reopen and re-download your ticket anytime here: <a href="${BASE_VOUCHER_URL}?voucher=${encodeURIComponent(voucherToken)}">${BASE_VOUCHER_URL}?voucher=${encodeURIComponent(voucherToken)}</a></p>`
          : '';
        MailApp.sendEmail({
          to: email,
          subject: `Your ticket to ${cfg.EventTitle || 'the event'} — ${serial}`,
          htmlBody: `<p>Hi ${fullName || ''},</p>` +
                    `<p>Your ticket to <strong>${cfg.EventTitle || 'the event'}</strong> (${cfg.ChapterName || ''}) is confirmed.</p>` +
                    `<p><strong>Serial:</strong> ${serial}<br><strong>Ticket type:</strong> ${tier}</p>` +
                    reopenLine
        });
      } catch (e) {
        // Never fail the actual claim just because the confirmation email couldn't send.
      }
    }

    return { ok: true, ticketNumber: String(nextNumber).padStart(3, '0'), serial: serial, tier: tier, checkInToken: checkInToken };

  } finally {
    lock.releaseLock();
  }
}

// ============================================================
// WEB ENTRY POINTS
// ============================================================

function doPost(e) {
  try {
    const body = JSON.parse(e.postData.contents);
    const action = body.action || 'claim';

    const routes = {
      verifyPasscode: verifyPasscodeWeb,
      adminGenerateVouchers: adminGenerateVouchersWeb,
      sendVoucher: sendVoucherWeb,
      checkInWithTicket: checkInWithTicketWeb,
      checkInWalkIn: checkInWalkInWeb,
      viewCheckInSummary: viewCheckInSummaryWeb,
      viewVoucherOverview: viewVoucherOverviewWeb,
      uploadLogo: uploadLogoWeb
    };
    if (routes[action]) return jsonResponse(routes[action](body));

    // default: a claimant submitting the claim form, with or without a voucher token
    const source = body.voucher ? 'voucher' : 'form';
    const result = issueTicket(
      body.fullName, body.email, body.phone, body.chapter, body.tier, source, body.voucher,
      undefined, !!body.confirmDuplicate
    );
    return jsonResponse(result);
  } catch (err) {
    return jsonResponse({ ok: false, error: err.message });
  }
}

function doGet(e) {
  const action = e.parameter && e.parameter.action;

  if (action === 'voucher') return jsonResponse(lookupVoucher(e.parameter.token));
  if (action === 'batch') return jsonResponse(lookupBatch(e.parameter.batch));
  if (action === 'config') return jsonResponse({ ok: true, tiers: getTierConfig(), event: getEventConfig(), groups: getGroups() });

  return jsonResponse({ ok: true, message: 'SLPP NE ticket backend is live.' });
}

/** Looks up one voucher for the claim page — what's prefilled, what's locked (tier only), or what it already resolved to if claimed. */
/** Looks up the stored secure check-in token for a given serial — used whenever an already-claimed ticket is redisplayed, so the QR stays consistent rather than regenerating (which would invalidate any copy the person already saved). */
function getCheckInTokenForSerial(serial) {
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(CLAIMS_SHEET_NAME);
    const lastRow = sheet.getLastRow();
    if (lastRow < 2) return null;
    const rows = sheet.getRange(2, 1, lastRow - 1, 11).getValues();
    const match = rows.find(row => (row[2] || '').toString().toUpperCase() === serial.toString().toUpperCase());
    return match ? (match[10] || null) : null;
  } catch (e) {
    return null;
  }
}

function lookupVoucher(token) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(VOUCHERS_SHEET_NAME);
  const data = sheet.getDataRange().getValues();
  for (let i = 1; i < data.length; i++) {
    if (data[i][0] === token) {
      const row = data[i];
      const claimed = row[10];
      if (claimed === true || claimed === 'TRUE') {
        const resultSerial = row[12] || null;
        return {
          ok: false, alreadyClaimed: true, error: 'This voucher has already been claimed.',
          serial: resultSerial, tier: row[13] || null,
          checkInToken: resultSerial ? getCheckInTokenForSerial(resultSerial) : null
        };
      }
      return { ok: true, name: row[4] || '', phone: row[5] || '', chapter: row[3] || '', tier: row[2] || '' };
    }
  }
  return { ok: false, error: 'This voucher link is not valid.' };
}

/** Lists every voucher in a batch — the distributor's view. */
function lookupBatch(batchId) {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(VOUCHERS_SHEET_NAME);
  const data = sheet.getDataRange().getValues();
  const vouchers = [];
  for (let i = 1; i < data.length; i++) {
    const row = data[i];
    if (row[1] === batchId) {
      vouchers.push({
        token: row[0],
        tier: row[2] || '',
        dispatched: row[8] === true || row[8] === 'TRUE',
        claimed: row[10] === true || row[10] === 'TRUE'
      });
    }
  }
  if (!vouchers.length) return { ok: false, error: 'This distributor link is not valid.' };
  return { ok: true, vouchers: vouchers };
}

// ============================================================
// ADMIN: GENERATE VOUCHERS (unified — size 1 to 10, always a "batch")
// ============================================================

/**
 * One admin action always produces one distributor link. For a single
 * voucher, name/phone are stored as claimant hints. For a multi-voucher
 * batch, the same fields are treated as distributor contact details and
 * are returned to the admin page only; they are NOT copied onto each
 * voucher, so the eventual claimants still enter their own identities.
 */
/**
 * Checks a passcode with no other side effect — used by the web panel to
 * gate the Generate Vouchers and Check-In sections behind a real check,
 * not just a field that happens to sit there unverified.
 */
function verifyPasscodeWeb(body) {
  const issuedBy = requireAdmin(body.adminPasscode);
  if (!issuedBy) return { ok: false, error: 'Incorrect passcode.' };
  return { ok: true, issuedBy: issuedBy };
}

/**
 * Accepts a generic tierCounts map ({ tierKey: count, ... }) instead of
 * named fields — works with any number of tiers, since the tier keys
 * themselves come from the Settings sheet, not from this function.
 */
function adminGenerateVouchersWeb(body) {
  const issuedBy = requireAdmin(body.adminPasscode);
  if (!issuedBy) return { ok: false, error: 'Not recognized as an admin.' };

  const tierKeys = validTierKeys();
  const tierCountsInput = body.tierCounts || {};
  const counts = {};
  tierKeys.forEach(key => { counts[key] = Math.max(0, parseInt(tierCountsInput[key], 10) || 0); });
  const openCount = Math.max(0, parseInt(body.openCount, 10) || 0);

  const total = tierKeys.reduce((sum, key) => sum + counts[key], 0) + openCount;
  const maxBatch = Number(getEventConfig().MaxBatchSize) || 10;
  if (total < 1) return { ok: false, error: 'Enter at least one voucher across the tiers.' };
  if (total > maxBatch) return { ok: false, error: `Maximum ${maxBatch} vouchers per batch — you entered ${total}.` };

  const chapter = (body.chapter || '').toString().trim();
  const contactName = (body.recipientName || '').toString().trim();
  const contactPhone = (body.recipientPhone || '').toString().trim();
  // Only a batch of one may prefill claimant identity. For larger batches,
  // these values identify the distributor and must never be copied to all
  // vouchers, otherwise every claimant would open a form prefilled as the
  // distributor.
  const name = total === 1 ? contactName : '';
  const phone = total === 1 ? contactPhone : '';

  const batchId = Utilities.getUuid().split('-')[0];
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(VOUCHERS_SHEET_NAME);

  function addVoucher(tier) {
    const token = Utilities.getUuid().split('-')[0];
    sheet.appendRow([token, batchId, tier, chapter, name, phone, new Date(), issuedBy, false, '', false, '', '', '', '', '']);
  }
  tierKeys.forEach(key => { for (let i = 0; i < counts[key]; i++) addVoucher(key); });
  for (let i = 0; i < openCount; i++) addVoucher('');

  return {
    ok: true,
    distributorUrl: BASE_VOUCHER_URL + '?batch=' + encodeURIComponent(batchId),
    count: total,
    breakdown: Object.assign({}, counts, { open: openCount }),
    issuedBy: issuedBy,
    contactName: contactName,
    contactPhone: contactPhone,
    contactRole: total === 1 ? 'recipient' : 'distributor'
  };
}

/** Marks one voucher "sent" so a distributor can't accidentally give it to two people. The link itself keeps working for whoever received it. */
/**
 * Sends one voucher to a specific recipient — requires an email or phone
 * (at least one), since a voucher can't actually be distributed without
 * somewhere to send it. Records who it was sent to, and if an email was
 * given, sends the real email itself (Text/WhatsApp still open the
 * distributor's own device app pre-filled — there's no free server-side
 * way to send those without a paid third-party SMS/WhatsApp API).
 */
function sendVoucherWeb(body) {
  const token = (body.token || '').toString().trim();
  if (!token) return { ok: false, error: 'Missing voucher token.' };

  const email = (body.recipientEmail || '').toString().trim();
  const phone = (body.recipientPhone || '').toString().trim();
  if (!email && !phone) {
    return { ok: false, error: 'Enter an email or phone number for the recipient before sending.' };
  }

  // Serialize sends so two taps/devices cannot dispatch the same voucher
  // at the same moment.
  const lock = LockService.getScriptLock();
  lock.waitLock(10000);
  try {
    const ss = SpreadsheetApp.getActiveSpreadsheet();
    const sheet = ss.getSheetByName(VOUCHERS_SHEET_NAME);
    const data = sheet.getDataRange().getValues();

    for (let i = 1; i < data.length; i++) {
      if (data[i][0] === token) {
        const dispatched = data[i][8];
        const claimed = data[i][10];
        if (claimed === true || claimed === 'TRUE') {
          return { ok: false, error: 'This voucher has already been claimed.' };
        }
        if (dispatched === true || dispatched === 'TRUE') {
          return { ok: false, error: 'This voucher has already been sent.' };
        }

        const voucherUrl = BASE_VOUCHER_URL + '?voucher=' + encodeURIComponent(token);
        let emailSent = false;

        // For email, do not burn the voucher unless MailApp succeeds.
        if (email) {
          try {
            const cfg = getEventConfig();
            MailApp.sendEmail({
              to: email,
              subject: `Your ticket to ${cfg.EventTitle || 'the event'}`,
              htmlBody: `<p>You've been sent a ticket voucher for <strong>${cfg.EventTitle || 'the event'}</strong> (${cfg.ChapterName || ''}).</p>` +
                        `<p><a href="${voucherUrl}">Click here to claim your ticket</a></p>` +
                        `<p>${voucherUrl}</p>`
            });
            emailSent = true;
          } catch (e) {
            return { ok: false, error: 'Could not send the email: ' + e.message };
          }
        }

        sheet.getRange(i + 1, 9).setValue(true);         // Dispatched
        sheet.getRange(i + 1, 10).setValue(new Date()); // Dispatched At
        sheet.getRange(i + 1, 15).setValue(email);       // Sent To Email
        sheet.getRange(i + 1, 16).setValue(phone);       // Sent To Phone

        return { ok: true, url: voucherUrl, emailSent: emailSent };
      }
    }
    return { ok: false, error: 'Voucher not found.' };
  } finally {
    lock.releaseLock();
  }
}

// ============================================================
// GATE: CHECK-IN (event day, separate concern from ticket issuance)
// ============================================================

/** A guest presenting an existing ticket. Looks up Claims by serial, logs a CheckIns row referencing it. */
function checkInWithTicketWeb(body) {
  const issuedBy = requireAdmin(body.adminPasscode);
  if (!issuedBy) return { ok: false, error: 'Not recognized as an admin.' };

  const rawInput = (body.serial || '').toString().trim();
  if (!rawInput) return { ok: false, error: 'Enter a ticket number or scan a QR code.' };

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const claimsSheet = ss.getSheetByName(CLAIMS_SHEET_NAME);
  const lastClaimsRow = claimsSheet.getLastRow();
  if (lastClaimsRow < 2) return { ok: false, error: 'Ticket number not found.' };
  const claims = claimsSheet.getRange(2, 1, lastClaimsRow - 1, 11).getValues();

  // A scanned QR encodes the long secure Check-In Token, not the human
  // serial — try an exact match on that first, since that's the path that
  // actually resists guessing. Manual typing falls back to the serial,
  // which is short and guessable by design, but has a staff member watching.
  let claim = claims.find(row => (row[10] || '').toString() === rawInput);
  let targetSerial;

  if (claim) {
    targetSerial = (claim[2] || '').toString().toUpperCase();
  } else {
    const digits = digitsOnly(rawInput);
    if (!digits) return { ok: false, error: "That doesn't look like a ticket number or QR code." };
    const prefix = getEventConfig().SerialPrefix || 'MA-';
    targetSerial = (prefix + digits.padStart(3, '0')).toUpperCase();
    claim = claims.find(row => (row[2] || '').toString().toUpperCase() === targetSerial);
    if (!claim) return { ok: false, error: 'Ticket number ' + targetSerial + ' not found.' };
  }

  const checkinsSheet = ss.getSheetByName(CHECKINS_SHEET_NAME);
  const lastCheckinRow = checkinsSheet.getLastRow();
  if (lastCheckinRow > 1) {
    const existing = checkinsSheet.getRange(2, 1, lastCheckinRow - 1, 8).getValues();
    const already = existing.find(row => (row[6] || '').toString().toUpperCase() === targetSerial);
    if (already) {
      return {
        ok: false, alreadyCheckedIn: true, error: 'This ticket has already been checked in.',
        name: already[1], chapter: already[2], tier: already[3]
      };
    }
  }

  const name = claim[4], chapter = claim[7], tier = claim[3];
  const phone = (body.phone || '').toString().trim() || claim[6] || '';
  const paymentStatus = body.paymentStatus === 'Pending' ? 'Pending' : 'Paid';

  checkinsSheet.appendRow([new Date(), name, chapter, tier, phone, paymentStatus, targetSerial, issuedBy]);
  return { ok: true, name: name, chapter: chapter, tier: tier, serial: targetSerial, paymentStatus: paymentStatus };
}

/** A walk-in with no prior ticket: issues a real ticket AND logs the check-in in one step. */
function checkInWalkInWeb(body) {
  const issuedBy = requireAdmin(body.adminPasscode);
  if (!issuedBy) return { ok: false, error: 'Not recognized as an admin.' };

  const fullName = (body.fullName || '').toString().trim();
  const chapter = (body.chapter || '').toString().trim();
  const tier = (body.tier || '').toString().trim().toLowerCase();
  const phone = (body.phone || '').toString().trim();
  const paymentStatus = body.paymentStatus === 'Pending' ? 'Pending' : 'Paid';

  if (!fullName) return { ok: false, error: 'Name is required.' };
  if (!chapter) return { ok: false, error: 'Chapter is required.' };
  if (!validTierKeys().includes(tier)) return { ok: false, error: 'Ticket type is required.' };

  const issued = issueTicket(fullName, '', phone, chapter, tier, 'walkin', null, issuedBy);
  if (!issued.ok) return issued;

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const checkinsSheet = ss.getSheetByName(CHECKINS_SHEET_NAME);
  checkinsSheet.appendRow([new Date(), fullName, chapter, issued.tier, phone, paymentStatus, issued.serial, issuedBy]);

  return { ok: true, name: fullName, chapter: chapter, tier: issued.tier, serial: issued.serial, paymentStatus: paymentStatus, checkInToken: issued.checkInToken };
}

/** Summarizes everyone checked in so far, grouped by chapter, with paid/pending tallies. */
/** Every ticket ever issued (any source: form, voucher, admin, walk-in), grouped by chapter, with the claimant's name. */
/**
 * Full funnel view, grouped by chapter: who's actually gotten a ticket
 * (issued — name, tier, serial, how it was issued) AND what's still
 * outstanding (pending — generated but not yet claimed, whether or not
 * it's been sent to someone). Pulls from Claims (issued) and Vouchers
 * (anything not yet Claimed there is still pending).
 */
function viewVoucherOverviewWeb(body) {
  const issuedBy = requireAdmin(body.adminPasscode);
  if (!issuedBy) return { ok: false, error: 'Not recognized as an admin.' };

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const claimsSheet = ss.getSheetByName(CLAIMS_SHEET_NAME);
  const vouchersSheet = ss.getSheetByName(VOUCHERS_SHEET_NAME);

  const byChapter = {};
  function bucket(chapter) {
    const key = (chapter || '').toString().trim() || 'Chapter not yet chosen';
    if (!byChapter[key]) byChapter[key] = { issued: [], pending: [] };
    return byChapter[key];
  }

  let totalIssued = 0, totalPending = 0;

  const claimsLast = claimsSheet.getLastRow();
  if (claimsLast > 1) {
    claimsSheet.getRange(2, 1, claimsLast - 1, 10).getValues().forEach(row => {
      bucket(row[7] || 'No Chapter').issued.push({ name: row[4], tier: row[3], serial: row[2], source: row[8] });
      totalIssued++;
    });
  }

  const vouchersLast = vouchersSheet.getLastRow();
  if (vouchersLast > 1) {
    vouchersSheet.getRange(2, 1, vouchersLast - 1, 14).getValues().forEach(row => {
      const claimed = row[10] === true || row[10] === 'TRUE';
      if (claimed) return; // already represented above, via Claims
      const dispatched = row[8] === true || row[8] === 'TRUE';
      bucket(row[3] || '').pending.push({
        tier: row[2] || '',
        name: row[4] || '',
        status: dispatched ? 'Sent — awaiting claim' : 'Not yet sent'
      });
      totalPending++;
    });
  }

  return { ok: true, totalIssued: totalIssued, totalPending: totalPending, byChapter: byChapter };
}

function viewCheckInSummaryWeb(body) {
  const issuedBy = requireAdmin(body.adminPasscode);
  if (!issuedBy) return { ok: false, error: 'Not recognized as an admin.' };

  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(CHECKINS_SHEET_NAME);
  const lastRow = sheet.getLastRow();

  const byChapter = {};
  let total = 0, paidTotal = 0, pendingTotal = 0;

  if (lastRow > 1) {
    const rows = sheet.getRange(2, 1, lastRow - 1, 8).getValues();
    rows.forEach(row => {
      const chapter = (row[2] || 'No Chapter').toString().trim() || 'No Chapter';
      const paid = row[5] === 'Paid';
      if (!byChapter[chapter]) byChapter[chapter] = { paid: 0, pending: 0, people: [] };
      byChapter[chapter].people.push({ name: row[1], tier: row[3], serial: row[6], paymentStatus: row[5] });
      if (paid) { byChapter[chapter].paid++; paidTotal++; } else { byChapter[chapter].pending++; pendingTotal++; }
      total++;
    });
  }

  return { ok: true, total: total, paidTotal: paidTotal, pendingTotal: pendingTotal, byChapter: byChapter };
}

// ============================================================
// SHEET-MENU CONVENIENCE WRAPPERS (same logic, prompt-based UI)
// ============================================================

function menuGenerateVouchers() {
  const ui = SpreadsheetApp.getUi();
  const passResp = ui.prompt('Generate Vouchers — Step 1', 'Your admin passcode:', ui.ButtonSet.OK_CANCEL);
  if (passResp.getSelectedButton() !== ui.Button.OK) return;
  const adminPasscode = passResp.getResponseText().trim();

  const tierConfig = getTierConfig();
  const tierKeys = Object.keys(tierConfig);
  const tierCounts = {};
  let step = 2;
  for (const key of tierKeys) {
    const cfg = tierConfig[key];
    const r = ui.prompt(`Step ${step} of ${tierKeys.length + 2}`, `How many ${cfg.label} ($${cfg.price})?`, ui.ButtonSet.OK_CANCEL);
    if (r.getSelectedButton() !== ui.Button.OK) return;
    tierCounts[key] = r.getResponseText().trim();
    step++;
  }

  const o = ui.prompt(`Step ${step} of ${tierKeys.length + 2}`, 'How many with NO fixed tier (recipient picks)?', ui.ButtonSet.OK_CANCEL);
  if (o.getSelectedButton() !== ui.Button.OK) return;
  const openCount = o.getResponseText().trim();
  step++;

  const c = ui.prompt(`Step ${step} of ${tierKeys.length + 2} (optional)`, 'Group/chapter to suggest — blank lets recipient(s) choose:', ui.ButtonSet.OK_CANCEL);
  if (c.getSelectedButton() !== ui.Button.OK) return;
  const chapter = c.getResponseText().trim();

  const result = adminGenerateVouchersWeb({ adminPasscode, tierCounts, openCount, chapter });
  if (!result.ok) { ui.alert('Could not generate', result.error, ui.ButtonSet.OK); return; }
  const b = result.breakdown;
  const breakdownText = tierKeys.map(k => `${b[k]} ${tierConfig[k].label}`).join(', ') + `, ${b.open} no fixed tier.`;
  ui.alert(
    'Vouchers generated — copy and send it',
    result.distributorUrl + `\n\n${breakdownText}` + `\n\nIssued by: ${result.issuedBy}`,
    ui.ButtonSet.OK
  );
}

function menuCheckInWithTicket() {
  const ui = SpreadsheetApp.getUi();
  const passResp = ui.prompt('Check In — Guest With Ticket', 'Your admin passcode:', ui.ButtonSet.OK_CANCEL);
  if (passResp.getSelectedButton() !== ui.Button.OK) return;
  const adminPasscode = passResp.getResponseText().trim();

  const serialResp = ui.prompt('Ticket number:', 'e.g. MA-007 or just 007', ui.ButtonSet.OK_CANCEL);
  if (serialResp.getSelectedButton() !== ui.Button.OK) return;
  const serial = serialResp.getResponseText().trim();

  const result = checkInWithTicketWeb({ adminPasscode, serial });
  if (!result.ok) { ui.alert(result.alreadyCheckedIn ? 'Already checked in' : 'Not found', result.error, ui.ButtonSet.OK); return; }
  ui.alert('Checked in ✅', `${result.name} — ${result.tier} — ${result.chapter} (${result.serial})`, ui.ButtonSet.OK);
}

function menuCheckInWalkIn() {
  const ui = SpreadsheetApp.getUi();
  const passResp = ui.prompt('Check In — Walk-In', 'Your admin passcode:', ui.ButtonSet.OK_CANCEL);
  if (passResp.getSelectedButton() !== ui.Button.OK) return;
  const adminPasscode = passResp.getResponseText().trim();

  const nameResp = ui.prompt('Guest full name:', '', ui.ButtonSet.OK_CANCEL);
  if (nameResp.getSelectedButton() !== ui.Button.OK) return;
  const fullName = nameResp.getResponseText().trim();

  const chapterResp = ui.prompt('Chapter (required):', 'Type exactly, e.g. "No Chapter" or "Arizona Chapter (AZC)"', ui.ButtonSet.OK_CANCEL);
  if (chapterResp.getSelectedButton() !== ui.Button.OK) return;
  const chapter = chapterResp.getResponseText().trim();

  const tierResp = ui.prompt('Ticket type (required):', validTierKeys().join(' / '), ui.ButtonSet.OK_CANCEL);
  if (tierResp.getSelectedButton() !== ui.Button.OK) return;
  const tier = tierResp.getResponseText().trim().toLowerCase();

  const phoneResp = ui.prompt('Phone (optional):', '', ui.ButtonSet.OK_CANCEL);
  if (phoneResp.getSelectedButton() !== ui.Button.OK) return;
  const phone = phoneResp.getResponseText().trim();

  const payResp = ui.prompt('Payment status:', 'Paid or Pending', ui.ButtonSet.OK_CANCEL);
  if (payResp.getSelectedButton() !== ui.Button.OK) return;
  const paymentStatus = /pending/i.test(payResp.getResponseText().trim()) ? 'Pending' : 'Paid';

  const result = checkInWalkInWeb({ adminPasscode, fullName, chapter, tier, phone, paymentStatus });
  if (!result.ok) { ui.alert('Could not check in', result.error, ui.ButtonSet.OK); return; }
  ui.alert('Sold & checked in ✅', `${result.name} — ${result.tier} — ${result.chapter} (${result.serial}) — ${result.paymentStatus}`, ui.ButtonSet.OK);
}

function menuViewCheckInSummary() {
  const ui = SpreadsheetApp.getUi();
  const passResp = ui.prompt('View Check-In Summary', 'Your admin passcode:', ui.ButtonSet.OK_CANCEL);
  if (passResp.getSelectedButton() !== ui.Button.OK) return;
  const adminPasscode = passResp.getResponseText().trim();

  const result = viewCheckInSummaryWeb({ adminPasscode });
  if (!result.ok) { ui.alert('Could not load summary', result.error, ui.ButtonSet.OK); return; }

  let msg = `${result.total} checked in total (${result.paidTotal} paid, ${result.pendingTotal} pending)\n\n`;
  Object.keys(result.byChapter).sort().forEach(chapter => {
    const c = result.byChapter[chapter];
    msg += `${chapter}: ${c.people.length} (${c.paid} paid, ${c.pending} pending)\n`;
  });
  ui.alert('Check-In Summary', msg, ui.ButtonSet.OK);
}

function adminShowNextNumber() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const current = Number(ss.getSheetByName(COUNTER_SHEET_NAME).getRange('A1').getValue()) || 0;
  const prefix = getEventConfig().SerialPrefix || 'MA-';
  SpreadsheetApp.getUi().alert('Ticket Status', `${current} issued so far.\nNext number: ${prefix}${String(current + 1).padStart(3, '0')}`, SpreadsheetApp.getUi().ButtonSet.OK);
}

// ============================================================
// DASHBOARDS
// ============================================================

function refreshDashboards() {
  buildClaimsVsVouchersChart();
  buildClaimsByChapterChart();
  buildVouchersByStatusChart();
  buildTicketsByTierChart();
  buildRevenueByChapterChart();
  SpreadsheetApp.getUi().alert('Dashboards refreshed', 'All five charts have been updated with the latest counts.', SpreadsheetApp.getUi().ButtonSet.OK);
}

function buildClaimsVsVouchersChart() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const totalClaims = Math.max(ss.getSheetByName(CLAIMS_SHEET_NAME).getLastRow() - 1, 0);
  const totalVouchers = Math.max(ss.getSheetByName(VOUCHERS_SHEET_NAME).getLastRow() - 1, 0);

  let dash = ss.getSheetByName('Claims vs Vouchers');
  if (!dash) dash = ss.insertSheet('Claims vs Vouchers');
  dash.getCharts().forEach(c => dash.removeChart(c));
  dash.clear();
  dash.getRange('A1:B1').setValues([['Metric', 'Count']]);
  dash.getRange('A2:B3').setValues([['Claims', totalClaims], ['Vouchers', totalVouchers]]);

  const chart = dash.newChart()
    .setChartType(Charts.ChartType.BAR)
    .addRange(dash.getRange('A1:B3'))
    .setPosition(5, 1, 0, 0)
    .setOption('title', 'Claims vs Vouchers Generated')
    .setOption('legend', { position: 'none' })
    .setOption('width', 600).setOption('height', 350)
    .build();
  dash.insertChart(chart);
}

function buildClaimsByChapterChart() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const claimsSheet = ss.getSheetByName(CLAIMS_SHEET_NAME);
  const lastRow = claimsSheet.getLastRow();

  const counts = {};
  if (lastRow > 1) {
    claimsSheet.getRange(2, 8, lastRow - 1, 1).getValues().forEach(r => {
      const ch = (r[0] || 'No Chapter').toString().trim() || 'No Chapter';
      counts[ch] = (counts[ch] || 0) + 1;
    });
  }

  let sheet = ss.getSheetByName('Claims by Chapter');
  if (!sheet) sheet = ss.insertSheet('Claims by Chapter');
  sheet.getCharts().forEach(c => sheet.removeChart(c));
  sheet.clear();
  sheet.getRange(1, 1, 1, 2).setValues([['Chapter', 'Claims']]);
  const rows = Object.keys(counts).sort().map(ch => [ch, counts[ch]]);
  if (rows.length) sheet.getRange(2, 1, rows.length, 2).setValues(rows);

  const chart = sheet.newChart()
    .setChartType(Charts.ChartType.BAR)
    .addRange(sheet.getRange(1, 1, rows.length + 1, 2))
    .setPosition(rows.length + 4, 1, 0, 0)
    .setOption('title', 'Claims by Chapter')
    .setOption('legend', { position: 'none' })
    .setOption('width', 700).setOption('height', Math.max(350, rows.length * 30))
    .build();
  sheet.insertChart(chart);
}

/** Where vouchers actually stand: claimed, sent-but-unclaimed, or never sent. Shows if generation is outpacing conversion. */
function buildVouchersByStatusChart() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(VOUCHERS_SHEET_NAME);
  const lastRow = sheet.getLastRow();

  let claimed = 0, sentUnclaimed = 0, notSent = 0;
  if (lastRow > 1) {
    sheet.getRange(2, 1, lastRow - 1, 14).getValues().forEach(row => {
      const isClaimed = row[10] === true || row[10] === 'TRUE';
      const isDispatched = row[8] === true || row[8] === 'TRUE';
      if (isClaimed) claimed++;
      else if (isDispatched) sentUnclaimed++;
      else notSent++;
    });
  }

  let dash = ss.getSheetByName('Vouchers by Status');
  if (!dash) dash = ss.insertSheet('Vouchers by Status');
  dash.getCharts().forEach(c => dash.removeChart(c));
  dash.clear();
  dash.getRange('A1:B1').setValues([['Status', 'Count']]);
  dash.getRange('A2:B4').setValues([['Claimed', claimed], ['Sent, awaiting claim', sentUnclaimed], ['Not yet sent', notSent]]);

  const chart = dash.newChart()
    .setChartType(Charts.ChartType.BAR)
    .addRange(dash.getRange('A1:B4'))
    .setPosition(6, 1, 0, 0)
    .setOption('title', 'Vouchers by Status')
    .setOption('legend', { position: 'none' })
    .setOption('width', 600).setOption('height', 350)
    .build();
  dash.insertChart(chart);
}

/** Ticket counts by tier — useful for catering/seating headcounts by price point. */
function buildTicketsByTierChart() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(CLAIMS_SHEET_NAME);
  const lastRow = sheet.getLastRow();

  const counts = { single: 0, patron: 0, double: 0 };
  if (lastRow > 1) {
    sheet.getRange(2, 4, lastRow - 1, 1).getValues().forEach(r => {
      const t = (r[0] || '').toString().toLowerCase();
      if (counts[t] !== undefined) counts[t]++;
    });
  }

  let dash = ss.getSheetByName('Tickets by Tier');
  if (!dash) dash = ss.insertSheet('Tickets by Tier');
  dash.getCharts().forEach(c => dash.removeChart(c));
  dash.clear();
  dash.getRange('A1:B1').setValues([['Tier', 'Count']]);
  dash.getRange('A2:B4').setValues([['Single ($100)', counts.single], ['Patron ($150)', counts.patron], ['Double ($250)', counts.double]]);

  const chart = dash.newChart()
    .setChartType(Charts.ChartType.BAR)
    .addRange(dash.getRange('A1:B4'))
    .setPosition(6, 1, 0, 0)
    .setOption('title', 'Tickets by Tier')
    .setOption('legend', { position: 'none' })
    .setOption('width', 600).setOption('height', 350)
    .build();
  dash.insertChart(chart);
}

/**
 * ESTIMATED revenue by chapter — ticket count × face value ($100/$150/$250).
 * This is an estimate, not a confirmed-payment figure: this system only
 * tracks actual Paid/Pending status for gate check-ins (CheckIns sheet),
 * not for online claims, which have no payment step at all.
 */
function buildRevenueByChapterChart() {
  const tierConfig = getTierConfig();
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const sheet = ss.getSheetByName(CLAIMS_SHEET_NAME);
  const lastRow = sheet.getLastRow();

  const revenue = {};
  if (lastRow > 1) {
    sheet.getRange(2, 1, lastRow - 1, 10).getValues().forEach(row => {
      const tier = (row[3] || '').toString().toLowerCase();
      const chapter = (row[7] || 'No Chapter').toString().trim() || 'No Chapter';
      const price = (tierConfig[tier] && tierConfig[tier].price) || 0;
      revenue[chapter] = (revenue[chapter] || 0) + price;
    });
  }

  let sheetOut = ss.getSheetByName('Revenue by Chapter');
  if (!sheetOut) sheetOut = ss.insertSheet('Revenue by Chapter');
  sheetOut.getCharts().forEach(c => sheetOut.removeChart(c));
  sheetOut.clear();
  sheetOut.getRange(1, 1, 1, 2).setValues([['Chapter', 'Estimated Revenue ($)']]);
  const rows = Object.keys(revenue).sort().map(ch => [ch, revenue[ch]]);
  if (rows.length) sheetOut.getRange(2, 1, rows.length, 2).setValues(rows);

  const chart = sheetOut.newChart()
    .setChartType(Charts.ChartType.BAR)
    .addRange(sheetOut.getRange(1, 1, rows.length + 1, 2))
    .setPosition(rows.length + 4, 1, 0, 0)
    .setOption('title', 'Estimated Revenue by Chapter (face value, not confirmed payment)')
    .setOption('legend', { position: 'none' })
    .setOption('width', 700).setOption('height', Math.max(350, rows.length * 30))
    .build();
  sheetOut.insertChart(chart);
}

/**
 * Run this ONCE (Sheet menu → "Create Configuration Form"). Builds a
 * Google Form covering every EventConfig field, all tiers (up to 5), the
 * groups list and optional image URLs. Logo file attachments are uploaded
 * separately on config.html because FormApp cannot create file-upload questions.
 * Responses land in a
 * sheet named "ConfigFormResponses" — getEventConfig()/getTierConfig()/
 * getGroups() all read the MOST RECENT submission from there automatically.
 * Submitting the form again updates the live configuration; nothing here
 * requires touching a Sheet cell directly.
 */
function createConfigForm() {
  const ss = SpreadsheetApp.getActiveSpreadsheet();
  const existingNames = ss.getSheets().map(s => s.getName());

  const form = FormApp.create('Event Configuration');
  form.setDescription(
    'Configure this event\'s branding, ticket tiers, and groups. ' +
    'Submitting this form again creates a NEW response — the most recent one is what the system actually uses.'
  );

  const text = (title, help) => form.addTextItem().setTitle(title).setHelpText(help || '');
  const para = (title, help) => form.addParagraphTextItem().setTitle(title).setHelpText(help || '');

  text('OrgName', 'e.g. SLPP North America');
  text('ChapterName', 'e.g. New England Chapter');
  text('EventTitle', 'e.g. Executive Inauguration Celebration');
  para('Tagline', 'Optional subtitle shown under the event title on the ticket');
  text('EventDate', 'e.g. Saturday, August 22, 2026');
  text('EventTime', 'e.g. 6:00 PM');
  text('VenueName');
  text('VenueAddress');
  text('ContactPhone');
  text('WebsiteURL');
  text('DressCode');
  text('PrimaryColor', 'Hex code, e.g. #0b3d24');
  text('GoldColor', 'Hex code, e.g. #c9a24b');
  text('SerialPrefix', 'e.g. MA-');
  text('CurrencySymbol', 'e.g. $');
  text('FooterLegalText', 'Small print on the ticket, e.g. refund policy');
  text('MaxBatchSize', 'Max vouchers per admin-generated batch, e.g. 10');

  form.addMultipleChoiceItem().setTitle('UseGroups')
    .setHelpText('Does this event use a grouping category (chapter/team/table)?')
    .setChoiceValues(['true', 'false']);
  text('GroupLabel', 'What to call the grouping — e.g. Chapter, Team, Table');
  para('GroupsList', 'One group name per line. Leave blank if UseGroups is false.');

  for (let i = 1; i <= 5; i++) {
    text(`Tier${i}Name`, `Optional — leave blank to skip. e.g. Single`);
    text(`Tier${i}Price`, `Price for tier ${i}, numbers only`);
  }

  // Google Apps Script FormApp cannot create a file-upload question programmatically.
  // A logo can be uploaded directly on config.html (recommended), or a public image URL can be pasted here.
  text('LogoURL', 'Optional public image URL. For an image attachment instead, use the Logo Upload section on config.html.');
  text('BackgroundURL', 'Optional public ticket background image URL.');

  form.setDestination(FormApp.DestinationType.SPREADSHEET, ss.getId());

  // Find whichever sheet Forms just created and rename it to something stable,
  // since getLatestFormResponse() reads by this exact name.
  const newSheets = ss.getSheets().filter(s => !existingNames.includes(s.getName()));
  if (newSheets.length) newSheets[0].setName(CONFIG_FORM_RESPONSES_SHEET);

  SpreadsheetApp.getUi().alert(
    'Configuration form created',
    'Editor link (manage the form):\n' + form.getEditUrl() +
    '\n\nPublished link (send this to whoever fills it out):\n' + form.getPublishedUrl() +
    '\n\nFile uploads land in a Drive folder tied to this form — the system reads the uploaded file directly, no extra steps needed.',
    SpreadsheetApp.getUi().ButtonSet.OK
  );
}

function jsonResponse(obj) {
  return ContentService.createTextOutput(JSON.stringify(obj)).setMimeType(ContentService.MimeType.JSON);
}
